.TH NAMGEN 1 "2026" "touchy" 
.SH NAME
touchy
.SH SYNOPSIS
.B watch the keyboard and disable trackpad when keyboard activity is noticed 
[OPTIONS]
.SH AUTHOR
Written by Joshua Edward McLaughlin Cox
.SH "REPORTING BUGS"
Report bugs to the project maintainers.
.SH "COPYRIGHT"
Copyright © 2026 touchy  developers
.LP
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
