#!/bin/bash
checkrc() {
  TARGETRC=$1
  if [[ -f ${HOME}/.${TARGETRC} ]]; then
    source .${TARGETRC}
  fi
}
checkrc ${HOME}/.touchyrc
checkrc ${HOME}/.config/touchy/touchyrc

# config values can be overridden by env vars
: "${TOUCHPAD:=asuf1209:00-2808:0219-touchpad}"
: "${GAME_MODE_SEMAFORE_FILE:=/tmp/.game_mode_on}"
: "${TOUCHY_LOGFILE:=/tmp/.touchy.log}"
: "${TOUCHY_SINGLETON_LOCK:=/tmp/.touchy.lock}"
: ${TOUCHY_LOGLEVEL:=0}
: ${TOUCHY_VERBOSITY:=1}
: ${TOUCHY_DELAY:=1}

logger() {
  MSG_LEVEL=$1
  if [[ ${MSG_LEVEL} -gt ${TOUCHY_VERBOSITY} ]]; then
    echo "${MSG}"
  fi
  if [[ ${MSG_LEVEL} -gt ${TOUCHY_LOGLEVEL} ]]; then
    echo "${MSG}" >>${TOUCHY_LOGFILE}
  fi
}

check_singleton_lock() {
  if [[ -f ${TOUCHY_SINGLETON_LOCK} ]]; then
    TOUCHY_SINGLETON_DEATH=1
    logger 100 'TOUCHY singleton lock found!'
    ps aux | grep touchy >>${TOUCHY_LOGFILE}
  else
    touch ${TOUCHY_SINGLETON_LOCK}
  fi
  if [[ -f ${TOUCHY_LOGFILE} ]]; then
    TOUCHY_SINGLETON_DEATH=1
    logger 100 'TOUCHY already running!'
    printenv >>${TOUCHY_LOGFILE}
  fi
  echo "PID $$ $0 $@" >>${TOUCHY_LOGFILE}
  date -I >>${TOUCHY_LOGFILE}
  if [[ TOUCHY_SINGLETON_DEATH -eq 1 ]]; then
    exit 1
  fi
}
check_singleton_lock

# initializers not to be edited
TIMER_PID=""
STATUS="enabled"

sleep 1

if [[ ${TOUCHY_VERBOSITY} -gt 0 ]]; then
  notify-send "Touchpad Debug" "Monitoring keyboard input layers..." --icon=input-touchpad --expire-time=2000
fi

# Stream global input event logs filtered by keyboard key presses
libinput debug-events | grep --line-buffered "KEYBOARD_.*pressed" | while read -r line; do

  if [[ -f "${GAME_MODE_SEMAFORE_FILE}" ]]; then
    if [[ ${TOUCHY_VERBOSITY} -gt 100 ]]; then
      logger 1 "game_mode_on skipping"
    fi
  else
    # If the touchpad is on, lock it out immediately
    if [[ "$STATUS" -eq "enabled" ]]; then
      hyprctl keyword "device[$TOUCHPAD]:enabled" false
      STATUS="disabled"
      if [[ ${TOUCHY_VERBOSITY} -gt 4 ]]; then
        logger 1 "Touchpad Status ❌ Touchpad DISABLED (Typing...) --icon=input-touchpad --expire-time=1000"
      fi
      if [[ ${TOUCHY_VERBOSITY} -gt 3 ]]; then
        notify-send "Touchpad Status" "❌ Touchpad DISABLED (Typing...)" --icon=input-touchpad --expire-time=1000
      fi
    fi
  fi

  # Drop older concurrent active background sleep timers
  if [[ -n "$TIMER_PID" ]]; then
    kill "$TIMER_PID" 2>/dev/null
  fi

  # Setup a clean background thread to revert back once typing pauses
  (
    sleep "$TOUCHY_DELAY"
    if [[ "$STATUS" -eq "disabled" ]]; then
      hyprctl keyword "device[$TOUCHPAD]:enabled" true
      if [[ ${TOUCHY_VERBOSITY} -gt 2 ]]; then
        logger 1 "Touchpad Status ✅ Touchpad ENABLED --icon=input-touchpad --expire-time=1000"
      fi
      if [[ ${TOUCHY_VERBOSITY} -gt 1 ]]; then
        notify-send "Touchpad Status" "✅ Touchpad ENABLED" --icon=input-touchpad --expire-time=1000
      fi
      STATUS="enabled"
    fi
  ) &
  TIMER_PID=$!
done
